# -*- coding: utf-8 -*-
"""ClaseUno.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gdeskANSrVGThecAfbMeRpIUhjk1rjBi
"""

# Sorprende a tus compañeros
import random
albums = ["The Court of the Crimson King", "The Dark Side of The Moon", "Appetite for Destruction", "¯Nevermind", "Wish you were here"]
guitar = ["Slash", "Brian May", "Jimi Hendrix", "Eric Clapton", "Van Halen"]
while True:
    ask = input("Eligue entre Album y Guitarrista  ")
    if ask == "Guitarrista":
        print(random.choice(guitar))
    elif ask == "Album":
        print(random.choice(albums))

import random
meme_dict = {
            "LOL": "una respuesta a algo gracioso",
            "CRINGE": "algo raro o embarazoso",
            "ROFL": "una respuesta a una broma",
            "SHEESH": "ligera desaprobación",
            "CREEPY": "aterrador, siniestro",
            "AGGRO": "ponerse agresivo/enojado",
            "SYBAU": "mandar a callar"
            }
word = input("Escribe una palabra que no entiendas (¡con mayúsculas!): ")
if word in meme_dict.keys():
    print(meme_dict[word])
else:
    print("palabra no encontrada en el diccionario")

