# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gdeskANSrVGThecAfbMeRpIUhjk1rjBi
"""

# Sorprende a tus compañeros
import random
albums = ["The Court of the Crimson King", "The Dark Side of The Moon", "Appetite for Destruction", "¯Nevermind", "Wish you were here"]
guitar = ["Slash", "Brian May", "Jimi Hendrix", "Eric Clapton", "Van Halen"]
while True:
    ask = input("Eligue entre Album y Guitarrista  ")
    if ask == "Guitarrista":
        print(random.choice(guitar))
    elif ask == "Album":
        print(random.choice(albums))